name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: |
          git config --global user.name drgy
          git config --global user.email drgonjak@gmail.com
      - run: npm ci
      - run: npm run build
      - run: |
          git add -Af build/*/.*
          git commit -m "Update production"
          git push origin `git subtree split --prefix build main`:production --force
